name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest # Usaremos Windows como sistema operativo

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Java a su versión 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft' # Usamos Microsoft OpenJDK para Windows

      # Paso 3: Almacenar en caché las dependencias de Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Paso 4: Compilar el proyecto con Maven
      - name: Build with Maven
        run: mvn clean install

      # Paso 5: Ejecutar las pruebas con Maven
      - name: Run tests
        run: mvn test